# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-18 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20180518_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='url_list',
            field=models.ManyToManyField(blank=True, default=[], to='links.Links'),
        ),
    ]
