# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-29 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20180518_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='url_list',
        ),
    ]
