# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_remove_season_url_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug_name', models.SlugField(max_length=350)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_series', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.MovieSeries'),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
