# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-29 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20180529_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
